// Auto-generated from 03-08-2026_Beat_Reporter_List.xlsx — 212 reporters
// userId fields start as null — fill them in after running:
//   node scripts/lookup-ids.js

const REPORTERS = [
  { name: "Kevin Chouinard", handle: "KLChouinard", userId: null, outlet: "Hawks.com / Zone Coverage", team: "Atlanta Hawks", tier: 1, signal: "High", conf: "E", notes: "Primary beat; fastest on Hawks injury news; daily practice access" },
  { name: "Lauren L. Williams", handle: "williamslaurenl", userId: null, outlet: "Atlanta Journal-Constitution", team: "Atlanta Hawks", tier: 1, signal: "High", conf: "E", notes: "AJC beat; strong locker-room sourcing" },
  { name: "Sarah K. Spencer", handle: "sarah_k_spencer", userId: null, outlet: "Atlanta Journal-Constitution", team: "Atlanta Hawks", tier: 2, signal: "Medium", conf: "E", notes: "AJC co-beat; detailed practice notes" },
  { name: "Chris Kirschner", handle: "ChrisKirschner", userId: null, outlet: "The Athletic", team: "Atlanta Hawks", tier: 2, signal: "High", conf: "E", notes: "Covers Hawks for The Athletic; breaks news regularly" },
  { name: "Quenton Albertie", handle: "QuentonAlbertie", userId: null, outlet: "Last Word On Sports", team: "Atlanta Hawks", tier: 3, signal: "Medium", conf: "E", notes: "Credentialed Hawks media member; covers games regularly" },
  { name: "Joe Barberio", handle: "JoeBarberio", userId: null, outlet: "FanDuel Sports Network SE", team: "Atlanta Hawks", tier: 3, signal: "Medium", conf: "E", notes: "Local TV sideline; locker-room access" },
  { name: "Jay King", handle: "ByJayKing", userId: null, outlet: "The Athletic", team: "Boston Celtics", tier: 1, signal: "High", conf: "E", notes: "Premier Celtics beat; breaks injury news very fast" },
  { name: "Chris Forsberg", handle: "ChrisForsberg_", userId: null, outlet: "NBC Sports Boston", team: "Boston Celtics", tier: 1, signal: "High", conf: "E", notes: "Daily practice coverage; very detailed injury reporting" },
  { name: "Gary Washburn", handle: "GaryWashburn", userId: null, outlet: "Boston Globe", team: "Boston Celtics", tier: 1, signal: "High", conf: "E", notes: "Veteran Globe columnist; strong team sourcing" },
  { name: "Adam Himmelsbach", handle: "adamhimmelsbach", userId: null, outlet: "Boston Globe", team: "Boston Celtics", tier: 1, signal: "High", conf: "E", notes: "Globe beat writer; co-covers with Washburn" },
  { name: "Brian Robb", handle: "BrianTRobb", userId: null, outlet: "MassLive", team: "Boston Celtics", tier: 2, signal: "Medium", conf: "E", notes: "Daily Celtics coverage; good practice reports" },
  { name: "John Karalis", handle: "john_karalis", userId: null, outlet: "WEEI / Red's Army", team: "Boston Celtics", tier: 2, signal: "Medium", conf: "E", notes: "Strong Celtics sourcing; well-connected locally" },
  { name: "A. Sherrod Blakely", handle: "SherrodBlakely", userId: null, outlet: "NBC Boston", team: "Boston Celtics", tier: 2, signal: "Medium", conf: "E", notes: "Veteran Celtics voice; locker-room access" },
  { name: "Tim Bontemps", handle: "TimBontemps", userId: null, outlet: "ESPN", team: "Boston Celtics", tier: 2, signal: "High", conf: "E", notes: "ESPN national reporter; strong Celtics sourcing" },
  { name: "Erik Slater", handle: "erikslater_", userId: null, outlet: "ClutchPoints", team: "Brooklyn Nets", tier: 1, signal: "High", conf: "E", notes: "Most plugged-in Nets reporter; very fast on injuries" },
  { name: "Alex Schiffer", handle: "Alex__Schiffer", userId: null, outlet: "The Athletic", team: "Brooklyn Nets", tier: 1, signal: "High", conf: "E", notes: "The Athletic Nets beat; strong injury reporting" },
  { name: "Brian Lewis", handle: "NYPost_Lewis", userId: null, outlet: "New York Post", team: "Brooklyn Nets", tier: 1, signal: "High", conf: "E", notes: "NY Post Nets beat; locker-room access" },
  { name: "Kristian Winfield", handle: "Krisplashed", userId: null, outlet: "NY Daily News", team: "Brooklyn Nets", tier: 2, signal: "High", conf: "E", notes: "Covers both NY teams; fast on injury news" },
  { name: "Ryan Rudominer", handle: "RyanRudominer", userId: null, outlet: "NetsDaily / FanSided", team: "Brooklyn Nets", tier: 2, signal: "Medium", conf: "E", notes: "Active Nets digital coverage; credentialed" },
  { name: "Ethan Sears", handle: "EthanJSears", userId: null, outlet: "New York Post", team: "Brooklyn Nets", tier: 2, signal: "Medium", conf: "E", notes: "NY Post Nets contributor; regular coverage" },
  { name: "Rod Boone", handle: "rodboone", userId: null, outlet: "The Athletic", team: "Charlotte Hornets", tier: 1, signal: "High", conf: "E", notes: "Most connected Hornets reporter; primary beat" },
  { name: "Rick Bonnell", handle: "rick_bonnell", userId: null, outlet: "Charlotte Observer", team: "Charlotte Hornets", tier: 1, signal: "High", conf: "E", notes: "Decades on the Hornets beat; excellent sourcing" },
  { name: "James Plowright", handle: "british_buzz", userId: null, outlet: "Locked On Hornets", team: "Charlotte Hornets", tier: 2, signal: "Medium", conf: "E", notes: "Credentialed; active daily Hornets coverage" },
  { name: "Wynton McLaurin", handle: "WyntonMcLaurin", userId: null, outlet: "WCCB Charlotte", team: "Charlotte Hornets", tier: 2, signal: "Medium", conf: "E", notes: "Local TV; locker-room access" },
  { name: "Mike Eisenberg", handle: "MikeEisenberg_", userId: null, outlet: "Hornets Beat", team: "Charlotte Hornets", tier: 2, signal: "Medium", conf: "E", notes: "Regular credentialed Hornets digital coverage" },
  { name: "Steve Reed", handle: "SteveReedAP", userId: null, outlet: "Associated Press", team: "Charlotte Hornets", tier: 2, signal: "High", conf: "E", notes: "AP Charlotte-based reporter; covers Hornets regularly" },
  { name: "KC Johnson", handle: "KCJHoop", userId: null, outlet: "Chicago Sports Network", team: "Chicago Bulls", tier: 1, signal: "High", conf: "E", notes: "Dean of Bulls reporters; best injury source by far" },
  { name: "Julia Poe", handle: "byjuliapoe", userId: null, outlet: "Chicago Tribune", team: "Chicago Bulls", tier: 1, signal: "High", conf: "E", notes: "Tribune beat; active daily practice coverage" },
  { name: "Colleen Kane", handle: "colleenkaneCT", userId: null, outlet: "Chicago Tribune", team: "Chicago Bulls", tier: 2, signal: "Medium", conf: "E", notes: "Tribune co-beat; covers Bulls regularly" },
  { name: "Rob Schaefer", handle: "rob_schaef", userId: null, outlet: "NBC Sports Chicago", team: "Chicago Bulls", tier: 2, signal: "High", conf: "E", notes: "NBC Chicago Bulls reporter; strong locker-room access" },
  { name: "Darnell Mayberry", handle: "DarnellMayberry", userId: null, outlet: "The Athletic", team: "Chicago Bulls", tier: 2, signal: "High", conf: "E", notes: "The Athletic Bulls senior writer" },
  { name: "Sam Smith", handle: "SamSmithHoops", userId: null, outlet: "Bulls.com", team: "Chicago Bulls", tier: 2, signal: "Medium", conf: "E", notes: "Official team site contributor; insider access" },
  { name: "Ben Pope", handle: "BenPopeCST", userId: null, outlet: "Chicago Sun-Times", team: "Chicago Bulls", tier: 2, signal: "Medium", conf: "E", notes: "Sun-Times Bulls coverage" },
  { name: "Chris Fedor", handle: "ChrisFedor", userId: null, outlet: "Cleveland Plain Dealer / cleveland.com", team: "Cleveland Cavaliers", tier: 1, signal: "High", conf: "E", notes: "Most plugged-in Cavs reporter; best injury source" },
  { name: "Joe Vardon", handle: "joevardon", userId: null, outlet: "The Athletic", team: "Cleveland Cavaliers", tier: 1, signal: "High", conf: "E", notes: "The Athletic Cavs beat; strong injury sourcing" },
  { name: "Kelsey Russo", handle: "kelseyyrusso", userId: null, outlet: "The Athletic", team: "Cleveland Cavaliers", tier: 1, signal: "High", conf: "E", notes: "The Athletic co-beat; daily practice notes" },
  { name: "Evan Dammarell", handle: "AmnoteEvan", userId: null, outlet: "Fear The Sword", team: "Cleveland Cavaliers", tier: 2, signal: "High", conf: "E", notes: "Credentialed Cavs reporter; active coverage" },
  { name: "Dan Labbe", handle: "dan_labbe", userId: null, outlet: "cleveland.com", team: "Cleveland Cavaliers", tier: 2, signal: "Medium", conf: "E", notes: "Cleveland.com active Cavs coverage" },
  { name: "Camryn Justice", handle: "camijustice", userId: null, outlet: "WEWS NewsChannel 5", team: "Cleveland Cavaliers", tier: 2, signal: "Medium", conf: "E", notes: "Local TV Cavs reporter; locker-room access" },
  { name: "Omari Sankofa II", handle: "omarisankofa", userId: null, outlet: "Detroit Free Press", team: "Detroit Pistons", tier: 1, signal: "High", conf: "E", notes: "Lead Pistons reporter at the Freep" },
  { name: "Coty Davis", handle: "CotyDavis_24", userId: null, outlet: "Detroit Free Press", team: "Detroit Pistons", tier: 1, signal: "High", conf: "E", notes: "Freep co-beat with Sankofa" },
  { name: "James Edwards III", handle: "JLEdwardsIII", userId: null, outlet: "The Athletic", team: "Detroit Pistons", tier: 1, signal: "High", conf: "E", notes: "The Athletic Pistons beat; strong injury intel" },
  { name: "Rod Beard", handle: "detnewsRodBeard", userId: null, outlet: "Detroit News", team: "Detroit Pistons", tier: 2, signal: "Medium", conf: "E", notes: "Detroit News veteran; Pistons beat" },
  { name: "Vince Ellis", handle: "vinceeellis", userId: null, outlet: "Detroit Free Press", team: "Detroit Pistons", tier: 2, signal: "Medium", conf: "E", notes: "Freep Pistons contributor; active coverage" },
  { name: "Dana Gauruder", handle: "DanaGauruder", userId: null, outlet: "Detroit News", team: "Detroit Pistons", tier: 2, signal: "Medium", conf: "E", notes: "Detroit News Pistons co-coverage" },
  { name: "Dustin Dopirak", handle: "DustinDopirak", userId: null, outlet: "The Athletic", team: "Indiana Pacers", tier: 1, signal: "High", conf: "E", notes: "Top Pacers source; The Athletic primary beat" },
  { name: "Scott Agness", handle: "ScottAgness", userId: null, outlet: "FieldhouseFiles.com", team: "Indiana Pacers", tier: 1, signal: "High", conf: "E", notes: "Dedicated Pacers site; strong locker-room access" },
  { name: "James Boyd", handle: "RomeovilleKid", userId: null, outlet: "Indianapolis Star", team: "Indiana Pacers", tier: 2, signal: "High", conf: "E", notes: "Indy Star Pacers beat" },
  { name: "Tony East", handle: "TEastNBA", userId: null, outlet: "SI / Pacers Digest", team: "Indiana Pacers", tier: 2, signal: "Medium", conf: "E", notes: "Credentialed Pacers media" },
  { name: "Nate Taylor", handle: "ByNateTaylor", userId: null, outlet: "The Athletic", team: "Indiana Pacers", tier: 2, signal: "Medium", conf: "E", notes: "The Athletic Pacers supplemental coverage" },
  { name: "Mark Montieth", handle: "MontieMedia", userId: null, outlet: "Pacers.com", team: "Indiana Pacers", tier: 2, signal: "Medium", conf: "E", notes: "Official team site; insider practice access" },
  { name: "Ira Winderman", handle: "IraHeatBeat", userId: null, outlet: "South Florida Sun Sentinel", team: "Miami Heat", tier: 1, signal: "High", conf: "E", notes: "38 seasons covering the Heat; GOAT Heat reporter; injury GOAT source" },
  { name: "Anthony Chiang", handle: "Anthony_Chiang", userId: null, outlet: "Miami Herald", team: "Miami Heat", tier: 1, signal: "High", conf: "E", notes: "Herald primary beat; frequent injury updates" },
  { name: "Shandel Richardson", handle: "ShandelRich", userId: null, outlet: "Sun Sentinel", team: "Miami Heat", tier: 2, signal: "High", conf: "E", notes: "Sun Sentinel co-beat with Winderman" },
  { name: "Brady Hawk", handle: "BradyHawk305", userId: null, outlet: "ClutchPoints", team: "Miami Heat", tier: 2, signal: "Medium", conf: "E", notes: "Active daily Heat coverage; credentialed" },
  { name: "Tim Reynolds", handle: "ByTimReynolds", userId: null, outlet: "Associated Press", team: "Miami Heat", tier: 2, signal: "High", conf: "E", notes: "AP NBA reporter; South Florida-based; Heat coverage" },
  { name: "Jason Jackson", handle: "JacksonAndAudio", userId: null, outlet: "Heat TV", team: "Miami Heat", tier: 2, signal: "Medium", conf: "E", notes: "Heat TV host; strong locker-room access" },
  { name: "Eric Nehm", handle: "eric_nehm", userId: null, outlet: "The Athletic", team: "Milwaukee Bucks", tier: 1, signal: "High", conf: "E", notes: "Premier Bucks reporter; excellent injury intel" },
  { name: "Matt Velazquez", handle: "Matt_Velazquez", userId: null, outlet: "Milwaukee Journal Sentinel", team: "Milwaukee Bucks", tier: 1, signal: "High", conf: "E", notes: "Journal Sentinel primary Bucks beat" },
  { name: "Jim Owczarski", handle: "JimOwczarski", userId: null, outlet: "Milwaukee Journal Sentinel", team: "Milwaukee Bucks", tier: 2, signal: "High", conf: "E", notes: "JS co-beat; strong locker-room access" },
  { name: "James Bates", handle: "JamesBates_", userId: null, outlet: "Brew Hoop", team: "Milwaukee Bucks", tier: 2, signal: "Medium", conf: "E", notes: "Credentialed Bucks digital site" },
  { name: "Phoebe Arscott", handle: "PArscott_", userId: null, outlet: "Bally Sports Wisconsin", team: "Milwaukee Bucks", tier: 2, signal: "Medium", conf: "E", notes: "Local TV; game-day locker-room access" },
  { name: "Jaymes Langrehr", handle: "jlangrehr", userId: null, outlet: "WISN 12", team: "Milwaukee Bucks", tier: 2, signal: "Medium", conf: "E", notes: "Local TV Bucks reporter; credentialed" },
  { name: "Ian Begley", handle: "IanBegley", userId: null, outlet: "SNY", team: "New York Knicks", tier: 1, signal: "High", conf: "E", notes: "Most connected Knicks reporter; fastest on injuries" },
  { name: "Steve Popper", handle: "StevePopper", userId: null, outlet: "Newsday", team: "New York Knicks", tier: 1, signal: "High", conf: "E", notes: "Longest-tenured Knicks beat writer" },
  { name: "Kristian Winfield", handle: "Krisplashed", userId: null, outlet: "NY Daily News", team: "New York Knicks", tier: 1, signal: "High", conf: "E", notes: "Strong locker-room access; fast on news" },
  { name: "James Edwards III", handle: "JLEdwardsIII", userId: null, outlet: "The Athletic", team: "New York Knicks", tier: 1, signal: "High", conf: "E", notes: "The Athletic Knicks primary beat" },
  { name: "Fred Katz", handle: "FredKatz", userId: null, outlet: "The Athletic", team: "New York Knicks", tier: 2, signal: "High", conf: "E", notes: "Now national writer but deep Knicks sourcing" },
  { name: "Marc Berman", handle: "NYPost_Berman", userId: null, outlet: "New York Post", team: "New York Knicks", tier: 2, signal: "High", conf: "E", notes: "NY Post veteran Knicks writer" },
  { name: "Alan Hahn", handle: "alanhahn", userId: null, outlet: "MSG Network", team: "New York Knicks", tier: 2, signal: "Medium", conf: "E", notes: "MSG broadcast analyst; locker-room access" },
  { name: "Stefan Bondy", handle: "SBondyNYDN", userId: null, outlet: "NY Daily News", team: "New York Knicks", tier: 2, signal: "Medium", conf: "E", notes: "Daily News Knicks co-coverage" },
  { name: "Jason Beede", handle: "therealBeede", userId: null, outlet: "Orlando Sentinel", team: "Orlando Magic", tier: 1, signal: "High", conf: "E", notes: "Primary Magic beat writer" },
  { name: "Khobi Price", handle: "khobi_price", userId: null, outlet: "Orlando Sentinel", team: "Orlando Magic", tier: 1, signal: "High", conf: "E", notes: "Sentinel co-beat with Beede" },
  { name: "Evan Dunlap", handle: "EvanDunlap13", userId: null, outlet: "ClutchPoints", team: "Orlando Magic", tier: 2, signal: "Medium", conf: "E", notes: "Active credentialed Magic coverage" },
  { name: "Bo Churney", handle: "BoChurney", userId: null, outlet: "Locked On Magic", team: "Orlando Magic", tier: 2, signal: "Medium", conf: "E", notes: "Daily Magic credentialed reporter" },
  { name: "Josh Robbins", handle: "JoshuaBRobbins", userId: null, outlet: "The Athletic", team: "Orlando Magic", tier: 2, signal: "High", conf: "E", notes: "The Athletic; also covers Wizards and Magic" },
  { name: "Scott Anez", handle: "ScottAnez", userId: null, outlet: "AP", team: "Orlando Magic", tier: 2, signal: "Medium", conf: "E", notes: "AP Orlando-based reporter; covers Magic" },
  { name: "Keith Pompey", handle: "PompeyOnSixers", userId: null, outlet: "Philadelphia Inquirer", team: "Philadelphia 76ers", tier: 1, signal: "High", conf: "E", notes: "Dean of Sixers reporters; best injury source" },
  { name: "Kyle Neubeck", handle: "KyleNeubeck", userId: null, outlet: "PhillyVoice", team: "Philadelphia 76ers", tier: 1, signal: "High", conf: "E", notes: "Primary beat; strong daily locker-room access" },
  { name: "Rich Hofmann", handle: "rich_hofmann", userId: null, outlet: "The Athletic", team: "Philadelphia 76ers", tier: 1, signal: "High", conf: "E", notes: "The Athletic Sixers beat; excellent injury intel" },
  { name: "Gina Mizell", handle: "GinaMizell", userId: null, outlet: "Philadelphia Inquirer", team: "Philadelphia 76ers", tier: 2, signal: "High", conf: "E", notes: "Inquirer co-beat; good injury coverage" },
  { name: "Tony Jones", handle: "Tjonesonthenba", userId: null, outlet: "The Athletic", team: "Philadelphia 76ers", tier: 2, signal: "Medium", conf: "E", notes: "" },
  { name: "Derek Bodner", handle: "DerekBodner", userId: null, outlet: "The Athletic / IndyPHL", team: "Philadelphia 76ers", tier: 2, signal: "Medium", conf: "E", notes: "Strong Sixers sourcing; veteran local reporter" },
  { name: "Jonathan Wasserman", handle: "NBADraftWass", userId: null, outlet: "Bleacher Report", team: "Philadelphia 76ers", tier: 2, signal: "Medium", conf: "E", notes: "Strong Sixers personnel sourcing" },
  { name: "Josh Lewenberg", handle: "JLew1050", userId: null, outlet: "TSN", team: "Toronto Raptors", tier: 1, signal: "High", conf: "E", notes: "Premier Raptors reporter; very reliable on injuries" },
  { name: "Doug Smith", handle: "dougsmithstar", userId: null, outlet: "Toronto Star", team: "Toronto Raptors", tier: 1, signal: "High", conf: "E", notes: "Veteran Star Raptors beat writer" },
  { name: "Michael Grange", handle: "michaelgrange", userId: null, outlet: "Sportsnet", team: "Toronto Raptors", tier: 1, signal: "High", conf: "E", notes: "Sportsnet Raptors analyst and reporter" },
  { name: "Eric Koreen", handle: "ekoreen", userId: null, outlet: "The Athletic", team: "Toronto Raptors", tier: 2, signal: "High", conf: "E", notes: "The Athletic Raptors coverage" },
  { name: "Vivek Jacob", handle: "vivekjacob_", userId: null, outlet: "Sportsnet", team: "Toronto Raptors", tier: 2, signal: "High", conf: "E", notes: "Regular credentialed Raptors coverage" },
  { name: "Blake Murphy", handle: "BlakeMurphyODC", userId: null, outlet: "The Athletic / Raptors Republic", team: "Toronto Raptors", tier: 2, signal: "Medium", conf: "E", notes: "Strong Raptors sourcing; credentialed" },
  { name: "Josh Robbins", handle: "JoshuaBRobbins", userId: null, outlet: "The Athletic", team: "Washington Wizards", tier: 1, signal: "High", conf: "E", notes: "Primary Wizards source at The Athletic" },
  { name: "Ava Wallace", handle: "avarwallace", userId: null, outlet: "Washington Post", team: "Washington Wizards", tier: 1, signal: "High", conf: "E", notes: "Washington Post Wizards beat" },
  { name: "Bijan Todd", handle: "bijan_todd", userId: null, outlet: "NBC Sports Washington", team: "Washington Wizards", tier: 1, signal: "High", conf: "E", notes: "NBC Washington Wizards reporter" },
  { name: "Chase Hughes", handle: "ChaseHughesNBC", userId: null, outlet: "NBC Sports Washington", team: "Washington Wizards", tier: 2, signal: "Medium", conf: "E", notes: "Regular Wizards credentialed reporter" },
  { name: "Kareem Copeland", handle: "kareemcopeland", userId: null, outlet: "Washington Post", team: "Washington Wizards", tier: 2, signal: "Medium", conf: "E", notes: "WaPo co-beat coverage" },
  { name: "Zach Selby", handle: "ZachSelby_DC", userId: null, outlet: "Wizards.com", team: "Washington Wizards", tier: 2, signal: "Medium", conf: "E", notes: "Official team site; insider practice access" },
  { name: "Tim MacMahon", handle: "espn_macmahon", userId: null, outlet: "ESPN", team: "Dallas Mavericks", tier: 1, signal: "High", conf: "W", notes: "ESPN Mavs beat; top injury source for Dallas" },
  { name: "Brad Townsend", handle: "townbrad", userId: null, outlet: "Dallas Morning News", team: "Dallas Mavericks", tier: 1, signal: "High", conf: "W", notes: "DMN veteran Mavs beat; decades on beat" },
  { name: "Callie Caplan", handle: "CallieCaplan", userId: null, outlet: "Dallas Morning News", team: "Dallas Mavericks", tier: 1, signal: "High", conf: "W", notes: "DMN Mavs reporter; active injury coverage" },
  { name: "Grant Afseth", handle: "GrantAfseth", userId: null, outlet: "ClutchPoints", team: "Dallas Mavericks", tier: 2, signal: "High", conf: "W", notes: "Active daily Mavs coverage; credentialed" },
  { name: "Mike Curtis", handle: "MikeACurtis2", userId: null, outlet: "Dallas Morning News", team: "Dallas Mavericks", tier: 2, signal: "High", conf: "W", notes: "DMN Mavs contributor" },
  { name: "Eddie Sefko", handle: "ESefko", userId: null, outlet: "Dallas Morning News", team: "Dallas Mavericks", tier: 2, signal: "Medium", conf: "W", notes: "Longtime Mavs coverage veteran" },
  { name: "Tim Cato", handle: "tim_cato", userId: null, outlet: "ALLCITY", team: "Dallas Mavericks", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Saad Yousuf", handle: "SaadYousuf126", userId: null, outlet: "The Athletic", team: "Dallas Mavericks", tier: 2, signal: "High", conf: "W", notes: "The Athletic Mavs beat writer" },
  { name: "Bennett Durando", handle: "BennettDurando", userId: null, outlet: "Denver Post", team: "Denver Nuggets", tier: 1, signal: "High", conf: "W", notes: "Denver Post primary Nuggets beat" },
  { name: "Mike Singer", handle: "msinger", userId: null, outlet: "Denver Post", team: "Denver Nuggets", tier: 1, signal: "High", conf: "W", notes: "Denver Post co-beat; strong injury coverage" },
  { name: "Harrison Wind", handle: "HarrisonWind", userId: null, outlet: "DNVR Sports", team: "Denver Nuggets", tier: 2, signal: "High", conf: "W", notes: "DNVR Nuggets credentialed site; very active" },
  { name: "Adam Mares", handle: "adam_mares", userId: null, outlet: "104.3 The Fan", team: "Denver Nuggets", tier: 2, signal: "High", conf: "W", notes: "Local radio beat; daily access" },
  { name: "Chris Dempsey", handle: "chrisadempsey", userId: null, outlet: "Altitude Sports", team: "Denver Nuggets", tier: 2, signal: "Medium", conf: "W", notes: "Local TV reporter; game access" },
  { name: "Katy Winge", handle: "katywinge", userId: null, outlet: "Altitude Sports TV", team: "Denver Nuggets", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Ryan Blackburn", handle: "NBABlackburn", userId: null, outlet: "Mile High Sports", team: "Denver Nuggets", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Gina De La Vega", handle: "GinaDelaVega_", userId: null, outlet: "Altitude Sports TV", team: "Denver Nuggets", tier: 2, signal: "Medium", conf: "W", notes: "Altitude TV Nuggets sideline reporter" },
  { name: "Anthony Slater", handle: "anthonyVslater", userId: null, outlet: "ESPN", team: "Golden State Warriors", tier: 1, signal: "High", conf: "W", notes: "Left The Athletic for ESPN 2025; premier Warriors reporter" },
  { name: "Marcus Thompson", handle: "marcus_thompson", userId: null, outlet: "The Athletic", team: "Golden State Warriors", tier: 1, signal: "High", conf: "W", notes: "Veteran Warriors columnist; strong injury sourcing" },
  { name: "Dalton Johnson", handle: "DaltonJ_", userId: null, outlet: "NBC Sports Bay Area", team: "Golden State Warriors", tier: 2, signal: "High", conf: "W", notes: "Active daily Warriors practice reports" },
  { name: "Sam Gordon", handle: "bysamgordon", userId: null, outlet: "NBC Sports Bay Area", team: "Golden State Warriors", tier: 2, signal: "High", conf: "W", notes: "NBC Bay Area Warriors beat reporter" },
  { name: "Nick Friedell", handle: "NickFriedell", userId: null, outlet: "ESPN", team: "Golden State Warriors", tier: 2, signal: "High", conf: "W", notes: "ESPN Warriors reporter; supplements Slater" },
  { name: "Rusty Simmons", handle: "Rusty_SFChron", userId: null, outlet: "San Francisco Chronicle", team: "Golden State Warriors", tier: 2, signal: "Medium", conf: "W", notes: "Chronicle Warriors coverage" },
  { name: "Tim Kawkami", handle: "timkawakami", userId: null, outlet: "SF Standard", team: "Golden State Warriors", tier: 1, signal: "High", conf: "W", notes: "" },
  { name: "Monte Poole", handle: "montePooleNBCS", userId: null, outlet: "NBC Sports Bay Area", team: "Golden State Warriors", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Connor Letourneau", handle: "Con_Chron", userId: null, outlet: "San Francisco Chronicle", team: "Golden State Warriors", tier: 2, signal: "Medium", conf: "W", notes: "Chronicle Dubs beat; regular practice coverage" },
  { name: "Jonathan Feigen", handle: "Jonathan_Feigen", userId: null, outlet: "Houston Chronicle", team: "Houston Rockets", tier: 1, signal: "High", conf: "W", notes: "Decades on the beat; sole primary Rockets reporter" },
  { name: "Kelly Iko", handle: "KellyIko", userId: null, outlet: "The Athletic", team: "Houston Rockets", tier: 1, signal: "High", conf: "W", notes: "The Athletic Rockets beat; strong injury sourcing" },
  { name: "Ben DuBose", handle: "BenDuBose", userId: null, outlet: "Space City Home Network", team: "Houston Rockets", tier: 2, signal: "High", conf: "W", notes: "Active credentialed Rockets reporter" },
  { name: "Lachard Binkley", handle: "BinkleyHoops", userId: null, outlet: "Locked On Rockets", team: "Houston Rockets", tier: 2, signal: "Medium", conf: "W", notes: "Credentialed Rockets digital coverage" },
  { name: "Varun Shankar", handle: "ByVarunShankar", userId: null, outlet: "Houston Chronicle", team: "Houston Rockets", tier: 3, signal: "Medium", conf: "W", notes: "" },
  { name: "Adam Spolane", handle: "AdamSpolane", userId: null, outlet: "Sports Radio 610", team: "Houston Rockets", tier: 2, signal: "Medium", conf: "W", notes: "Houston radio beat; locker-room access" },
  { name: "Jackson Gatlin", handle: "JacksonGatlin1", userId: null, outlet: "Clutch City Sports", team: "Houston Rockets", tier: 2, signal: "Medium", conf: "W", notes: "Credentialed Rockets coverage" },
  { name: "Tomer Azarly", handle: "TomerAzarly", userId: null, outlet: "ClutchPoints", team: "LA Clippers", tier: 1, signal: "High", conf: "W", notes: "Most connected Clippers reporter; very fast on injuries" },
  { name: "Law Murray", handle: "LawMurrayTheNU", userId: null, outlet: "The Athletic", team: "LA Clippers", tier: 1, signal: "High", conf: "W", notes: "The Athletic Clippers beat; strong locker-room presence" },
  { name: "Joey Linn", handle: "joeylinn_", userId: null, outlet: "The Athletic", team: "LA Clippers", tier: 1, signal: "High", conf: "W", notes: "The Athletic co-beat; daily Clippers access" },
  { name: "Janis Carr", handle: "janiscarr", userId: null, outlet: "Los Angelas Daily News", team: "LA Clippers", tier: 3, signal: "Medium", conf: "W", notes: "" },
  { name: "Mirjam Swanson", handle: "MirjamSwanson", userId: null, outlet: "LA Daily News", team: "LA Clippers", tier: 2, signal: "Medium", conf: "W", notes: "Daily News Clippers coverage" },
  { name: "Andrew Greif", handle: "AndrewGreif", userId: null, outlet: "Los Angeles Times", team: "LA Clippers", tier: 2, signal: "High", conf: "W", notes: "LA Times Clippers beat" },
  { name: "Broderick Turner", handle: "BA_Turner", userId: null, outlet: "Los Angeles Times", team: "LA Clippers", tier: 2, signal: "Medium", conf: "W", notes: "LA Times Clippers contributor" },
  { name: "Mike Trudell", handle: "LakersReporter", userId: null, outlet: "Spectrum SportsNet", team: "Los Angeles Lakers", tier: 1, signal: "High", conf: "W", notes: "Most connected Lakers reporter; fastest on injuries" },
  { name: "Dan Woike", handle: "DanWoike", userId: null, outlet: "The Athletic", team: "Los Angeles Lakers", tier: 1, signal: "High", conf: "W", notes: "Replaced Buha at The Athletic on Lakers beat, June 2025" },
  { name: "Dave McMenamin", handle: "mcten", userId: null, outlet: "ESPN", team: "Los Angeles Lakers", tier: 1, signal: "High", conf: "W", notes: "ESPN Lakers insider; strong injury sourcing" },
  { name: "Kyle Goon", handle: "kylegoon", userId: null, outlet: "Southern California News Group", team: "Los Angeles Lakers", tier: 2, signal: "High", conf: "W", notes: "SCNG Lakers active beat writer" },
  { name: "Jovan Buha", handle: "jovanbuha", userId: null, outlet: "YouTube / Independent", team: "Los Angeles Lakers", tier: 2, signal: "High", conf: "W", notes: "Left The Athletic; continues covering Lakers independently" },
  { name: "Bill Oram", handle: "billoram", userId: null, outlet: "The Athletic", team: "Los Angeles Lakers", tier: 2, signal: "Medium", conf: "W", notes: "The Athletic Lakers supplemental coverage" },
  { name: "Ohm Youngmisuk", handle: "NotoriousOHM", userId: null, outlet: "ESPN", team: "Los Angeles Lakers", tier: 2, signal: "High", conf: "W", notes: "ESPN LA-based NBA reporter; covers Lakers" },
  { name: "Damichael Cole", handle: "DamichaelC", userId: null, outlet: "Memphis Commercial Appeal", team: "Memphis Grizzlies", tier: 1, signal: "High", conf: "W", notes: "Primary Grizzlies beat writer" },
  { name: "Drew Hill", handle: "DrewHill_DM", userId: null, outlet: "Memphis Commercial Appeal", team: "Memphis Grizzlies", tier: 1, signal: "High", conf: "W", notes: "Commercial Appeal co-beat" },
  { name: "Chris Herrington", handle: "ChrisHerrington", userId: null, outlet: "The Daily Memphian", team: "Memphis Grizzlies", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Evan Barnes", handle: "evan_b", userId: null, outlet: "Memphis Commercial Appeal", team: "Memphis Grizzlies", tier: 2, signal: "Medium", conf: "W", notes: "MCA Grizzlies supplemental coverage" },
  { name: "Joe Mullinax", handle: "sidelineSCOUT", userId: null, outlet: "GrizznessNBA", team: "Memphis Grizzlies", tier: 2, signal: "Medium", conf: "W", notes: "Credentialed Grizzlies digital coverage" },
  { name: "Jared Ramsey", handle: "JaredRamseyNBA", userId: null, outlet: "Grind City Media", team: "Memphis Grizzlies", tier: 2, signal: "Medium", conf: "W", notes: "Credentialed Grizzlies digital media" },
  { name: "Pete Pranica", handle: "PetePranica", userId: null, outlet: "FanDuel Sports Network", team: "Memphis Grizzlies", tier: 3, signal: "Medium", conf: "W", notes: "Grizzlies TV play-by-play; locker-room access" },
  { name: "Jon Krawczynski", handle: "JonKrawczynski", userId: null, outlet: "The Athletic", team: "Minnesota Timberwolves", tier: 1, signal: "High", conf: "W", notes: "Elite Wolves reporter; best NBA beat writer per many; top injury source" },
  { name: "Chris Hine", handle: "ChristopherHine", userId: null, outlet: "Minneapolis Star Tribune", team: "Minnesota Timberwolves", tier: 1, signal: "High", conf: "W", notes: "Star Tribune primary Wolves beat" },
  { name: "Dane Moore", handle: "DaneMooreNBA", userId: null, outlet: "Dane Moore NBA Podcast", team: "Minnesota Timberwolves", tier: 2, signal: "High", conf: "W", notes: "Credentialed Wolves media; very active on injuries" },
  { name: "Jace Frederick", handle: "JaceFrederick", userId: null, outlet: "Pioneer Press", team: "Minnesota Timberwolves", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Tina Winder", handle: "TinaWinder", userId: null, outlet: "Bally Sports North", team: "Minnesota Timberwolves", tier: 2, signal: "Medium", conf: "W", notes: "Local TV; locker-room access" },
  { name: "Michael Rand", handle: "RandBall", userId: null, outlet: "Minneapolis Star Tribune", team: "Minnesota Timberwolves", tier: 2, signal: "Medium", conf: "W", notes: "Star Tribune sports columnist; covers Wolves" },
  { name: "Kelly Vogel", handle: "KellyVogelNBA", userId: null, outlet: "KSTP", team: "Minnesota Timberwolves", tier: 2, signal: "Medium", conf: "W", notes: "Local TV Wolves reporter; credentialed" },
  { name: "Jim Eichenhofer", handle: "Jim_Eichenhofer", userId: null, outlet: "Pelicans.com", team: "New Orleans Pelicans", tier: 1, signal: "High", conf: "W", notes: "Official team site; unusually reliable; fast on injury news" },
  { name: "Will Guillory", handle: "WillGuillory", userId: null, outlet: "The Athletic", team: "New Orleans Pelicans", tier: 1, signal: "High", conf: "W", notes: "The Athletic Pelicans primary beat" },
  { name: "Christian Clark", handle: "cclark_13", userId: null, outlet: "New Orleans Times-Picayune", team: "New Orleans Pelicans", tier: 2, signal: "High", conf: "W", notes: "Times-Picayune Pelicans beat" },
  { name: "Oleh Kosel", handle: "OlehKosel", userId: null, outlet: "The Bird Writes", team: "New Orleans Pelicans", tier: 2, signal: "Medium", conf: "W", notes: "Credentialed digital Pelicans coverage" },
  { name: "Rod Walker", handle: "RodWalkerNBA", userId: null, outlet: "New Orleans Advocate", team: "New Orleans Pelicans", tier: 2, signal: "Medium", conf: "W", notes: "Advocate Pelicans beat writer" },
  { name: "Andrew Lopez", handle: "_Andrew_Lopez", userId: null, outlet: "ESPN", team: "New Orleans Pelicans", tier: 2, signal: "High", conf: "W", notes: "ESPN New Orleans-based Pelicans reporter" },
  { name: "Brandon Rahbar", handle: "BrandonRahbar", userId: null, outlet: "Daily Thunder", team: "Oklahoma City Thunder", tier: 1, signal: "High", conf: "W", notes: "Premier Thunder reporter; fastest on OKC injuries" },
  { name: "Joel Lorenzi", handle: "jxlorenzi", userId: null, outlet: "The Oklahoman", team: "Oklahoma City Thunder", tier: 1, signal: "High", conf: "W", notes: "Oklahoman primary Thunder beat writer; joined Oct 2023" },
  { name: "Rylan Stiles", handle: "Rylan_Stiles", userId: null, outlet: "Inside The Thunder / Locked On", team: "Oklahoma City Thunder", tier: 1, signal: "High", conf: "W", notes: "Credentialed; hosts Locked On Thunder; strong injury intel" },
  { name: "Justin Martinez", handle: "JMartNBA", userId: null, outlet: "The Oklahoman", team: "Oklahoma City Thunder", tier: 2, signal: "High", conf: "W", notes: "Oklahoman Thunder trending/coverage reporter" },
  { name: "Michael Martin", handle: "MichaelOnSports", userId: null, outlet: "Self Employed", team: "Oklahoma City Thunder", tier: 3, signal: "Medium", conf: "W", notes: "" },
  { name: "Joe Mussatto", handle: "JoeMussattoSCR", userId: null, outlet: "The Oklahoman", team: "Oklahoma City Thunder", tier: 2, signal: "Medium", conf: "W", notes: "Former Thunder beat; now columnist; still deep Thunder sourcing" },
  { name: "Gerald Bourguet", handle: "GeraldBourguet", userId: null, outlet: "PHNX Media", team: "Phoenix Suns", tier: 1, signal: "High", conf: "W", notes: "Top Suns reporter; breaks injury news first" },
  { name: "Duane Rankin", handle: "DuaneRankin", userId: null, outlet: "Arizona Republic", team: "Phoenix Suns", tier: 1, signal: "High", conf: "W", notes: "Arizona Republic Suns veteran" },
  { name: "Kellan Olson", handle: "kellanolson", userId: null, outlet: "Arizona Republic", team: "Phoenix Suns", tier: 2, signal: "High", conf: "W", notes: "Republic co-beat; active injury reporting" },
  { name: "John Gambadoro", handle: "Gambo987", userId: null, outlet: "Arizona Sports 98.7", team: "Phoenix Suns", tier: 2, signal: "Medium", conf: "W", notes: "Local radio; strong Suns sourcing" },
  { name: "Bo Brack", handle: "BoBrack", userId: null, outlet: "PHNX Sports", team: "Phoenix Suns", tier: 2, signal: "Medium", conf: "W", notes: "PHNX co-beat; regular practice coverage" },
  { name: "Ty Tasker", handle: "TyTasker", userId: null, outlet: "PHNX Sports", team: "Phoenix Suns", tier: 2, signal: "Medium", conf: "W", notes: "PHNX Suns contributor; credentialed" },
  { name: "Casey Holdahl", handle: "CHold", userId: null, outlet: "TrailBlazers.com", team: "Portland Trail Blazers", tier: 1, signal: "High", conf: "W", notes: "Team site; very detailed practice notes; Tier 1 reliability" },
  { name: "Jason Quick", handle: "jwquick", userId: null, outlet: "The Athletic", team: "Portland Trail Blazers", tier: 1, signal: "High", conf: "W", notes: "The Athletic Blazers beat veteran" },
  { name: "Sean Highkin", handle: "highkin", userId: null, outlet: "Rose Garden Report", team: "Portland Trail Blazers", tier: 2, signal: "High", conf: "W", notes: "Credentialed independent Blazers reporter" },
  { name: "Aaron Fentress", handle: "AaronJFentress", userId: null, outlet: "The Oregonian", team: "Portland Trail Blazers", tier: 2, signal: "Medium", conf: "W", notes: "Oregonian Blazers coverage" },
  { name: "Joe Freeman", handle: "BlazerFreeman", userId: null, outlet: "The Oregonian", team: "Portland Trail Blazers", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Jamie Hudson", handle: "JamieHudson_", userId: null, outlet: "NBC Sports Northwest", team: "Portland Trail Blazers", tier: 2, signal: "Medium", conf: "W", notes: "Local TV; locker-room access" },
  { name: "Kerry Eggers", handle: "KerryEggers", userId: null, outlet: "Portland Tribune", team: "Portland Trail Blazers", tier: 2, signal: "Medium", conf: "W", notes: "Portland Tribune; veteran Blazers beat" },
  { name: "James Ham", handle: "James_HamNBA", userId: null, outlet: "NBC Sports California", team: "Sacramento Kings", tier: 1, signal: "High", conf: "W", notes: "Most connected Kings reporter; decades on beat" },
  { name: "Jason Anderson", handle: "JandersonSacBee", userId: null, outlet: "Sacramento Bee", team: "Sacramento Kings", tier: 1, signal: "High", conf: "W", notes: "Sacramento Bee Kings primary beat" },
  { name: "Sean Cunningham", handle: "seancunningham45", userId: null, outlet: "ABC10 Sacramento", team: "Sacramento Kings", tier: 2, signal: "High", conf: "W", notes: "Local TV; strong locker-room access" },
  { name: "Frankie Cartoscelli", handle: "FCartoscelli3", userId: null, outlet: "Sactown Sports 1140", team: "Sacramento Kings", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Brenden Nunes", handle: "BrendenNunesNBA", userId: null, outlet: "Sactown Sports 1140", team: "Sacramento Kings", tier: 2, signal: "Medium", conf: "W", notes: "" },
  { name: "Mike Richman", handle: "MikeRichman", userId: null, outlet: "Kings.com", team: "Sacramento Kings", tier: 2, signal: "High", conf: "W", notes: "Official team site; good injury and practice detail" },
  { name: "Mychael Urban", handle: "MychealUrban", userId: null, outlet: "NBC Sports California", team: "Sacramento Kings", tier: 2, signal: "Medium", conf: "W", notes: "NBC CA Kings supplemental reporter" },
  { name: "Matt George", handle: "MattGeorge975", userId: null, outlet: "95.7 The Game / KHTK", team: "Sacramento Kings", tier: 2, signal: "Medium", conf: "W", notes: "Sacramento radio; locker-room access" },
  { name: "Jeff McDonald", handle: "JMcDonald_SAEN", userId: null, outlet: "San Antonio Express-News", team: "San Antonio Spurs", tier: 1, signal: "High", conf: "W", notes: "Lead Spurs beat writer at Express-News" },
  { name: "Tom Orsborn", handle: "tom_orsborn", userId: null, outlet: "San Antonio Express-News", team: "San Antonio Spurs", tier: 1, signal: "High", conf: "W", notes: "Express-News co-beat; strong practice notes" },
  { name: "Paul Garcia", handle: "PaulGarciaNBA", userId: null, outlet: "Project Spurs / Locked On", team: "San Antonio Spurs", tier: 2, signal: "High", conf: "W", notes: "Credentialed Spurs digital coverage" },
  { name: "Mike Finger", handle: "mikefinger", userId: null, outlet: "San Antonio Express-News", team: "San Antonio Spurs", tier: 2, signal: "Medium", conf: "W", notes: "SAEN sports columnist; Spurs-focused" },
  { name: "Jabari Young", handle: "JabariJYoung", userId: null, outlet: "CNBC / Sports Business", team: "San Antonio Spurs", tier: 2, signal: "Medium", conf: "W", notes: "Former Spurs beat; still well-sourced in SA" },
  { name: "Damian Arseneault", handle: "DamianArseneault", userId: null, outlet: "The Athletic", team: "San Antonio Spurs", tier: 2, signal: "High", conf: "W", notes: "The Athletic Spurs coverage" },
  { name: "Andy Larsen", handle: "andyblarsen", userId: null, outlet: "Salt Lake Tribune", team: "Utah Jazz", tier: 1, signal: "High", conf: "W", notes: "Top Jazz reporter; stat-savvy injury coverage" },
  { name: "Eric Walden", handle: "tribjazz", userId: null, outlet: "Salt Lake Tribune", team: "Utah Jazz", tier: 1, signal: "High", conf: "W", notes: "Tribune co-beat with Larsen" },
  { name: "Kevin Reynolds", handle: "Kevinreynolds30", userId: null, outlet: "Salt Lake Tribune", team: "Utah Jazz", tier: 3, signal: "Medium", conf: "W", notes: "" },
  { name: "Sarah Todd", handle: "NBASarah", userId: null, outlet: "KSL Sports", team: "Utah Jazz", tier: 2, signal: "High", conf: "W", notes: "KSL Sports Jazz beat" },
  { name: "Jody Genessy", handle: "DJJazzyJody", userId: null, outlet: "Deseret News", team: "Utah Jazz", tier: 2, signal: "High", conf: "W", notes: "Deseret News veteran Jazz reporter" },
  { name: "David Locke", handle: "DLocke_Jazz", userId: null, outlet: "Jazz Radio / KSL", team: "Utah Jazz", tier: 2, signal: "Medium", conf: "W", notes: "Official Jazz radio voice; strong locker-room presence" },
  { name: "Shams Charania", handle: "ShamsCharania", userId: null, outlet: "ESPN", team: "All Teams", tier: 1, signal: "High", conf: "NAT", notes: "Premier NBA insider; first on everything league-wide" },
  { name: "Marc Stein", handle: "TheSteinLine", userId: null, outlet: "Substack / Independent", team: "All Teams", tier: 1, signal: "High", conf: "NAT", notes: "Veteran insider; deep team-by-team sourcing" },
  { name: "Chris Haynes", handle: "ChrisBHaynes", userId: null, outlet: "TNT / Bleacher Report", team: "All Teams", tier: 1, signal: "High", conf: "NAT", notes: "Top-tier NBA insider; all teams" },
  { name: "Jake Fischer", handle: "JakeLFischer", userId: null, outlet: "Yahoo Sports", team: "All Teams", tier: 1, signal: "High", conf: "NAT", notes: "Strong NBA transaction & injury intel" },
  { name: "Sam Amick", handle: "sam_amick", userId: null, outlet: "The Athletic", team: "All Teams", tier: 1, signal: "High", conf: "NAT", notes: "The Athletic veteran insider; strong team sourcing" },
  { name: "Brian Windhorst", handle: "WindhorstESPN", userId: null, outlet: "ESPN", team: "All Teams", tier: 2, signal: "High", conf: "NAT", notes: "ESPN NBA analyst; frequent injury context" },
  { name: "Tim Bontemps", handle: "TimBontemps", userId: null, outlet: "ESPN", team: "All Teams", tier: 2, signal: "High", conf: "NAT", notes: "ESPN NBA reporter; multi-team coverage" },
  { name: "Keith Smith", handle: "KeithSmithNBA", userId: null, outlet: "Spotrac", team: "All Teams", tier: 2, signal: "High", conf: "NAT", notes: "Cap expert; tracks all personnel & injury-related moves" },
  { name: "Kevin O'Connor", handle: "KevinOConnorNBA", userId: null, outlet: "The Ringer", team: "All Teams", tier: 2, signal: "Medium", conf: "NAT", notes: "National analysis with injury context" },
  { name: "Jonathan Givony", handle: "DraftExpress", userId: null, outlet: "ESPN", team: "All Teams", tier: 3, signal: "Medium", conf: "NAT", notes: "Draft / player development intel" },
  { name: "Ramona Shelburne", handle: "ramonashelburne", userId: null, outlet: "ESPN", team: "All Teams", tier: 2, signal: "High", conf: "NAT", notes: "ESPN senior writer; deep sourcing across teams" },
];

module.exports = REPORTERS;
